/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chlopek.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/chlopek.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.mater} />
    </group>
  )
}

useGLTF.preload('./models/chlopek.glb')
